### ISSUE TITLE
Show post cover image on home/post/posts page

### ISSUE THREAD

**Issue by egoist** [saberland/create-portfolio#31]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/saberland/create-portfolio/issues/31)

Use the `assets.cover` attribute.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Submitted pull Requests
- [#124 feat(Post): Implement asset cover feature](https://issuehunt.io/r/saberland/create-portfolio/pull/124)
- [#94 feat(Post): Implement asset cover feature](https://issuehunt.io/r/saberland/create-portfolio/pull/94)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/create-portfolio/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by SpyTec** [comment]
I was wondering if this should be covering the whole top, as 100% width. Then have a transparent circle where the back to home button is

**Comment by SpyTec** [comment]
Thought of two concepts:

1: 
![image](https://user-images.githubusercontent.com/6598829/60250906-d4589600-98c7-11e9-8a06-25c103e1bd95.png)

which is using a div above the `div.wrap` element in post.vue, styling being:
```css
height: 350px;
background: url("https://www.bing.com/th?id=OHR.RootBridge_ROW5832767622_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp") center center;
background-size: cover;
```

as well as --bg color for the button's background instead of transparent.

2:
![image](https://user-images.githubusercontent.com/6598829/60251132-44ffb280-98c8-11e9-8cf3-fa72947652a2.png)

Same as above, but with `div.wrap` moved up and -100px and `div.column.is-6.is-offset-3` set to `background-color: var(--bg)`

**Comment by SpyTec** [comment]
@egoist thoughts on the above?

**Comment by quaj** [comment]
is this done?

**Comment by SpyTec** [comment]
It is not, @quaj do you have a preference of one of the two I posted or would you go a different route?

**Comment by quaj** [comment]
absolutely i thinks you misunderstand egoist mean
his issue too short, i think egoist mean is a option to create a cover for a post
something like this
```yml
---
title: Dear CO
layout: post
date: 2019-08-28
hero: ./images/hero.jpg
tags:
  - hello
```

**Comment by SpyTec** [comment]
Saber already has functionality for cover posts, all that is needed is displaying it. This ticket is primarily for the design on how this should look on home, posts, and post. 

Home and Posts isn't something I drafted up, but could look something like this:
![image](https://user-images.githubusercontent.com/6598829/63853260-8715a500-c99a-11e9-959a-d71d862d49f2.png)

**Comment by egoist** [comment]
@SpyTec For post page I prefer a minimal approach like: https://leo.im/2017/canary

![image](https://user-images.githubusercontent.com/8784712/65615011-3cb03400-dfeb-11e9-934b-024af19a9d95.png)

Maybe this could be an option for the theme: `coverLayout: 'minimal' | 'landscape'`

For home and posts page, your draft looks good.

**Comment by saltysugar** [comment]
@SpyTec Are you going to work on this?

**Comment by SpyTec** [comment]
@saltysugar I will work on it this weekend. But feel free to implement it before that
