### ISSUE TITLE
How to add skills logo?

### ISSUE THREAD

**Issue by rjworks** [saberland/create-portfolio#80]
I have in saber config:
``{
        topic: 'nodejs',
        description: `I love Node.js and I am pretty trash at it.`
      },
      {
        topic: 'skateboard',
        description: 'I like skateboarding. Skate or die!!!!!!!! hehe. I choose life.'
      }``
how do i add logo of skateboard?

**Comment by egoist** [comment]
Only GitHub topics are supported: https://github.com/saberland/create-portfolio#skills
